name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build-image
      run: docker build -t game-catalog .

    - name: create env file
      run: echo -e "MONGODB_URI=${MONGODB_URI}\nCONNECT_APPLICATION_CLIENT_ID=${CONNECT_APPLICATION_CLIENT_ID}\nCONNECT_APPLICATION_CLIENT_SECRET=${CONNECT_APPLICATION_CLIENT_SECRET}" > .env
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        CONNECT_APPLICATION_CLIENT_ID: ${{ secrets.CONNECT_APPLICATION_CLIENT_ID }}
        CONNECT_APPLICATION_CLIENT_SECRET: ${{ secrets.CONNECT_APPLICATION_CLIENT_SECRET }}

    - name: docker-compose-up
      run: docker-compose up -d

    - name: run tests
      run: docker-compose run taiko yarn jest
    
    - name: docker-compose-stop
      run: docker-compose stop
