name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build-image
      run: docker build -t game-catalog .

    - name: test-e2e
      run: docker-compose up -d && COMPOSE_INTERACTIVE_NO_CLI=1 docker-compose exec taiko yarn jest
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        CONNECT_APPLICATION_CLIENT_ID: ${{ secrets.CONNECT_APPLICATION_CLIENT_ID }}
        CONNECT_APPLICATION_CLIENT_SECRET: ${{ secrets.CONNECT_APPLICATION_CLIENT_SECRET }}
    
    - name: docker-compose-stop
      run: docker-compose stop
