name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build-image
      run: docker build -t game-catalog .

    - name: docker-compose-up
      run: docker-compose up -d


    - name: create env file
      run: echo "MONGODB_URI=${MONGODB_URI}\nCONNECT_APPLICATION_CLIENT_ID=${CONNECT_APPLICATION_CLIENT_ID}\nCONNECT_APPLICATION_CLIENT_SECRET=${CONNECT_APPLICATION_CLIENT_SECRET}" > .env
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        CONNECT_APPLICATION_CLIENT_ID: ${{ secrets.CONNECT_APPLICATION_CLIENT_ID }}
        CONNECT_APPLICATION_CLIENT_SECRET: ${{ secrets.CONNECT_APPLICATION_CLIENT_SECRET }}

    - name: test-e2e
      run: docker run -it -e URL="http://localhost:8080" --network="host" -v $(pwd)/tests:/app/tests fewlines/taiko:0.1.0 yarn jest
    
    - name: docker-compose-stop
      run: docker-compose stop
